source 'https://rubygems.org'

ruby '~> 3.4.8'

gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.5'
gem 'rack-cors'
gem 'dotenv-rails', groups: [:development, :test]
gem 'bcrypt', '~> 3.1.7'
gem 'tzinfo-data'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 6.0'
end

group :development do
  gem 'spring'
end

gem "jwt", "~> 3.1"
